using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DotNetLab
{
    class ExceptionHandling
    {
        //static void Main(string[] args)
        //{
        //    int num1, num2, result; 

        //    try
        //    {
        //        Console.Write("Enter first number: ");
        //        num1 = Convert.ToInt32(Console.ReadLine());

        //        Console.Write("Enter second number: ");
        //        num2 = Convert.ToInt32(Console.ReadLine());

        //        // Division Operations 
        //        result = num1 / num2; 

        //        Console.WriteLine($"Result: {num1} / {num2} = {result}"); 
        //    }
        //    catch(DivideByZeroException e) 
        //    {
        //        Console.WriteLine("Error: Division by zero is not allowed. ");
        //        Console.WriteLine("System Message: " + e.Message);
        //    }
        //    catch(FormatException e) 
        //    {
        //        Console.WriteLine("Error: Please enter a valid integer. ");
        //        Console.WriteLine("System Message: " + e.Message);
        //    }
        //    catch(Exception e) 
        //    {
        //        Console.WriteLine("An unexpected error occurred. ");
        //        Console.WriteLine("System Message: " + e.Message);
        //    }
        //    finally
        //    {
        //        Console.WriteLine("\nProgram execution completed.(finally block)");
        //    }
        //}
    }
}
